#define IDD_TRANSFER 4870100

#define IDC_TRANSFER_BACKGROUND    1
#define IDC_TRANSFER_TITLE         2
#define IDC_TRANSFER_SEARCH        3
#define IDC_TRANSFER_POOL          4
#define IDC_TRANSFER_POOLTITLE     5
#define IDC_TRANSFER_CONTAINER     6
#define IDC_TRANSFER_CONTAINERTITLE 7
#define IDC_TRANSFER_AMOUNT        8
#define IDC_TRANSFER_TOCONTAINER   9
#define IDC_TRANSFER_TOPOOL        10
#define IDC_TRANSFER_INFO          11
#define IDC_TRANSFER_CLOSE         12
